volumes:
  rocketchat-uploads:
  mongodb_data: { driver: local }
  traefik: { driver: local }

networks:
  network-rocketchat:
    external: true

services:
  rocketchat:
    image: rocket.chat:7.4.1
    volumes:
      - rocketchat-uploads:/app/uploads
    restart: always
    labels:
      traefik.enable: "true"
      traefik.http.routers.rocketchat.rule: Host(`chat.localhost`) || HostRegexp(`{any:.+}`)
      traefik.http.routers.rocketchat.entrypoints: web
      traefik.http.services.rocketchat.loadbalancer.server.port: 3000  # Direciona para porta 3000
    environment:
      MONGO_URL: mongodb://mongodb:27017/rocketchat?replicaSet=rs0
      MONGO_OPLOG_URL: mongodb://mongodb:27017/local?replicaSet=rs0
      ROOT_URL: http://chat.localhost
      PORT: 3000
      DEPLOY_METHOD: docker
    depends_on:
      - mongodb
      - traefik
    expose:
      - ${PORT:-3000}
    ports:
      - "${BIND_IP:-0.0.0.0}:${HOST_PORT:-3000}:${PORT:-3000}"
    networks:
      - network-rocketchat

  mongodb:
    image: docker.io/bitnami/mongodb:${MONGODB_VERSION:-6.0}
    restart: always
    volumes:
      - mongodb_data:/bitnami/mongodb
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: rs0
      MONGODB_PORT_NUMBER: 27017
      MONGODB_INITIAL_PRIMARY_HOST: mongodb
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: 27017
      MONGODB_ADVERTISED_HOSTNAME: mongodb
      MONGODB_ENABLE_JOURNAL: true
      ALLOW_EMPTY_PASSWORD: yes
    networks:
      - network-rocketchat

  traefik:
    image: docker.io/traefik:${TRAEFIK_RELEASE:-v2.9.8}
    restart: always
    command:
     - --log.level=WARN    
     - "--accesslog=true"       # Habilita log de requisições
     - --api.insecure=false
     - --providers.docker=true
     - --providers.docker.exposedbydefault=false
     - --entrypoints.web.address=:80
     - "--providers.docker.endpoint=unix:///var/run/docker.sock"
    labels:
      # Habilita Traefik para o container
      - "traefik.enable=true"
    ports:
      - 80:80
    volumes:
      - /run/docker.sock:/var/run/docker.sock:ro
      - "/var/log/traefik:/var/log/traefik"
    networks:
      - network-rocketchat